name: clickhouse-customer-support-lab

services:
  keeper:
    image: clickhouse/clickhouse-keeper:${KEEPER_VERSION}
    hostname: keeper
    volumes:
      - ./keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml:ro
      - keeper-data:/var/lib/clickhouse
    ports:
      - "9181:9181"
    restart: unless-stopped

  clickhouse1:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse1
    env_file:
      - .env.local
    depends_on:
      keeper:
        condition: service_started
    volumes:
      - ./clickhouse/config.d/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/node1/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/users.d/cluster_internal.xml:/etc/clickhouse-server/users.d/cluster_internal.xml:ro
      - clickhouse1-data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: unless-stopped

  clickhouse2:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    hostname: clickhouse2
    env_file:
      - .env.local
    depends_on:
      keeper:
        condition: service_started
    volumes:
      - ./clickhouse/config.d/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml:ro
      - ./clickhouse/node2/macros.xml:/etc/clickhouse-server/config.d/macros.xml:ro
      - ./clickhouse/users.d/cluster_internal.xml:/etc/clickhouse-server/users.d/cluster_internal.xml:ro
      - clickhouse2-data:/var/lib/clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"
    restart: unless-stopped

  kafka:
    image: apache/kafka:${KAFKA_VERSION}
    hostname: kafka

    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: HOST://0.0.0.0:9092,INTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,INTERNAL://kafka:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LOG_DIRS: /var/lib/kafka/data

      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

    volumes:
      - kafka-data:/var/lib/kafka/data

    ports:
      - "9092:9092"

    restart: unless-stopped

volumes:
  keeper-data:
  clickhouse1-data:
  clickhouse2-data:
  kafka-data:
