apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false

    jsonData:
      host: clickhouse1
      port: 9000
      protocol: native
      username: grafana_reader
      defaultDatabase: saas_analytics
      queryTimeout: 60

    secureJsonData:
      password: $CLICKHOUSE_GRAFANA_PASSWORD